-- MySQL Script generated by MySQL Workbench
-- Mon Nov  4 15:06:47 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema libraryDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `Addresses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Addresses` ;

CREATE TABLE IF NOT EXISTS `Addresses` (
  `addressID` INT UNSIGNED NOT NULL,
  `street_number` INT UNSIGNED NOT NULL,
  `street_name` VARCHAR(16) NOT NULL,
  `city` VARCHAR(16) NOT NULL,
  `state` VARCHAR(16) NOT NULL,
  `zipcode` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`addressID`),
  UNIQUE INDEX `addressID_UNIQUE` (`addressID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Public Libraries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Public Libraries` ;

CREATE TABLE IF NOT EXISTS `Public Libraries` (
  `libraryID` INT UNSIGNED NOT NULL,
  `county_name` VARCHAR(16) NOT NULL,
  `address` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`libraryID`),
  UNIQUE INDEX `county_name_UNIQUE` (`county_name` ASC) VISIBLE,
  INDEX `libraryAddress_idx` (`address` ASC) VISIBLE,
  UNIQUE INDEX `libraryID_UNIQUE` (`libraryID` ASC) VISIBLE,
  CONSTRAINT `libraryAddress`
    FOREIGN KEY (`address`)
    REFERENCES `Addresses` (`addressID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Apartments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Apartments` ;

CREATE TABLE IF NOT EXISTS `Apartments` (
  `apartmentID` INT UNSIGNED NOT NULL,
  `building_number` INT UNSIGNED NOT NULL,
  `apartment_number` INT UNSIGNED NOT NULL,
  UNIQUE INDEX `apartmentID_UNIQUE` (`apartmentID` ASC) INVISIBLE,
  PRIMARY KEY (`apartmentID`),
  CONSTRAINT `apartmentAddressID`
    FOREIGN KEY (`apartmentID`)
    REFERENCES `Addresses` (`addressID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `P.O. Boxes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `P.O. Boxes` ;

CREATE TABLE IF NOT EXISTS `P.O. Boxes` (
  `po_boxID` INT UNSIGNED NOT NULL,
  `po_box_number` INT UNSIGNED NOT NULL,
  `service_name` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`po_boxID`),
  UNIQUE INDEX `po_boxID_UNIQUE` (`po_boxID` ASC) VISIBLE,
  CONSTRAINT `poBoxAddressID`
    FOREIGN KEY (`po_boxID`)
    REFERENCES `Addresses` (`addressID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Library Branches`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Library Branches` ;

CREATE TABLE IF NOT EXISTS `Library Branches` (
  `branchID` INT UNSIGNED NOT NULL,
  `is_virtual` TINYINT NOT NULL,
  `libraryID` INT UNSIGNED NOT NULL,
  `address` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`branchID`),
  INDEX `countyLibraryID_idx` (`libraryID` ASC) VISIBLE,
  INDEX `branchAddressID_idx` (`address` ASC) VISIBLE,
  UNIQUE INDEX `branchID_UNIQUE` (`branchID` ASC) VISIBLE,
  CONSTRAINT `countyLibraryID`
    FOREIGN KEY (`libraryID`)
    REFERENCES `Public Libraries` (`libraryID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `branchAddressID`
    FOREIGN KEY (`address`)
    REFERENCES `Addresses` (`addressID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Libraries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Libraries` ;

CREATE TABLE IF NOT EXISTS `Libraries` (
  `libraryAddressID` INT UNSIGNED NOT NULL,
  `county_region` VARCHAR(16) NOT NULL,
  `branch` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`libraryAddressID`),
  INDEX `libraryBranchID_idx` (`branch` ASC) VISIBLE,
  UNIQUE INDEX `libraryAddressID_UNIQUE` (`libraryAddressID` ASC) VISIBLE,
  UNIQUE INDEX `branch_UNIQUE` (`branch` ASC) VISIBLE,
  CONSTRAINT `libraryBranchID`
    FOREIGN KEY (`branch`)
    REFERENCES `Library Branches` (`branchID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `libraryAddressID`
    FOREIGN KEY (`libraryAddressID`)
    REFERENCES `Addresses` (`addressID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Institutions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Institutions` ;

CREATE TABLE IF NOT EXISTS `Institutions` (
  `institutionID` INT UNSIGNED NOT NULL,
  `school_district` VARCHAR(16) NOT NULL,
  `school_name` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`institutionID`),
  UNIQUE INDEX `institutionID_UNIQUE` (`institutionID` ASC) VISIBLE,
  CONSTRAINT `institutionalAddressID`
    FOREIGN KEY (`institutionID`)
    REFERENCES `Addresses` (`addressID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Patrons`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Patrons` ;

CREATE TABLE IF NOT EXISTS `Patrons` (
  `libraryCardNumber` INT UNSIGNED NOT NULL,
  `email` VARCHAR(64) NOT NULL,
  `is_delinquent` TINYINT NOT NULL,
  PRIMARY KEY (`libraryCardNumber`),
  UNIQUE INDEX `libraryCardNumber_UNIQUE` (`libraryCardNumber` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `E-Cards`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `E-Cards` ;

CREATE TABLE IF NOT EXISTS `E-Cards` (
  `ecardID` INT UNSIGNED NOT NULL,
  `first_name` VARCHAR(32) NOT NULL,
  `last_name` VARCHAR(32) NOT NULL,
  `date_of_birth` DATE NOT NULL,
  PRIMARY KEY (`ecardID`),
  UNIQUE INDEX `ecardID_UNIQUE` (`ecardID` ASC) VISIBLE,
  CONSTRAINT `ecardNumber`
    FOREIGN KEY (`ecardID`)
    REFERENCES `Patrons` (`libraryCardNumber`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Full-Service Cards`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Full-Service Cards` ;

CREATE TABLE IF NOT EXISTS `Full-Service Cards` (
  `patronID` INT UNSIGNED NOT NULL,
  `first_name` VARCHAR(32) NOT NULL,
  `last_name` VARCHAR(32) NOT NULL,
  `date_of_birth` DATE NOT NULL,
  `phone_number` VARCHAR(16) NOT NULL,
  `address` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`patronID`),
  UNIQUE INDEX `fullServiceCardID_UNIQUE` (`patronID` ASC) VISIBLE,
  INDEX `patronAddress_idx` (`address` ASC) VISIBLE,
  CONSTRAINT `patronAddress`
    FOREIGN KEY (`address`)
    REFERENCES `Addresses` (`addressID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `patronCard`
    FOREIGN KEY (`patronID`)
    REFERENCES `Patrons` (`libraryCardNumber`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Child Cards`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Child Cards` ;

CREATE TABLE IF NOT EXISTS `Child Cards` (
  `childID` INT UNSIGNED NOT NULL,
  `first_name` VARCHAR(32) NOT NULL,
  `last_name` VARCHAR(32) NOT NULL,
  `date_of_birth` DATE NOT NULL,
  `parentID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`childID`),
  INDEX `parentLibraryCard_idx` (`parentID` ASC) VISIBLE,
  UNIQUE INDEX `childID_UNIQUE` (`childID` ASC) VISIBLE,
  CONSTRAINT `parentLibraryCard`
    FOREIGN KEY (`parentID`)
    REFERENCES `Full-Service Cards` (`patronID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `childCard`
    FOREIGN KEY (`childID`)
    REFERENCES `Patrons` (`libraryCardNumber`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Institutional Cards`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Institutional Cards` ;

CREATE TABLE IF NOT EXISTS `Institutional Cards` (
  `institutionalID` INT UNSIGNED NOT NULL,
  `first_name` VARCHAR(32) NOT NULL,
  `last_name` VARCHAR(32) NOT NULL,
  `phone_number` VARCHAR(16) NOT NULL,
  `address` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`institutionalID`),
  UNIQUE INDEX `institutionalCardID_UNIQUE` (`institutionalID` ASC) VISIBLE,
  INDEX `instituionalAddressID_idx` (`address` ASC) VISIBLE,
  CONSTRAINT `instituionalAddressID`
    FOREIGN KEY (`address`)
    REFERENCES `Addresses` (`addressID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `institutionalCard`
    FOREIGN KEY (`institutionalID`)
    REFERENCES `Patrons` (`libraryCardNumber`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Staff Cards`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Staff Cards` ;

CREATE TABLE IF NOT EXISTS `Staff Cards` (
  `staffID` INT UNSIGNED NOT NULL,
  `first_name` VARCHAR(32) NOT NULL,
  `last_name` VARCHAR(32) NOT NULL,
  `date_of_birth` DATE NOT NULL,
  `phone_number` VARCHAR(16) NOT NULL,
  `address` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`staffID`),
  UNIQUE INDEX `staffCardID_UNIQUE` (`staffID` ASC) VISIBLE,
  INDEX `staffAddressID_idx` (`address` ASC) VISIBLE,
  CONSTRAINT `staffAddressID`
    FOREIGN KEY (`address`)
    REFERENCES `Addresses` (`addressID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `staffCard`
    FOREIGN KEY (`staffID`)
    REFERENCES `Patrons` (`libraryCardNumber`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Items`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Items` ;

CREATE TABLE IF NOT EXISTS `Items` (
  `item_barcode_number` INT UNSIGNED NOT NULL,
  `call_number` VARCHAR(32) NOT NULL,
  `title` VARCHAR(32) NOT NULL,
  `owningBranch` INT UNSIGNED NULL,
  PRIMARY KEY (`item_barcode_number`),
  UNIQUE INDEX `itemBarcodeNumber_UNIQUE` (`item_barcode_number` ASC) VISIBLE,
  INDEX `owningBranchID_idx` (`owningBranch` ASC) VISIBLE,
  CONSTRAINT `owningBranchID`
    FOREIGN KEY (`owningBranch`)
    REFERENCES `Library Branches` (`branchID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Computers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Computers` ;

CREATE TABLE IF NOT EXISTS `Computers` (
  `computerID` INT UNSIGNED NOT NULL,
  `computer_number` INT UNSIGNED NOT NULL,
  `is_express` TINYINT NOT NULL,
  `is_laptop` TINYINT NOT NULL,
  `area` VARCHAR(32) NOT NULL,
  `descrption` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`computerID`),
  UNIQUE INDEX `computerID_UNIQUE` (`computerID` ASC) VISIBLE,
  CONSTRAINT `copmuterBarcodeNumber`
    FOREIGN KEY (`computerID`)
    REFERENCES `Items` (`item_barcode_number`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AV`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AV` ;

CREATE TABLE IF NOT EXISTS `AV` (
  `avID` INT UNSIGNED NOT NULL,
  `content_length` TIME NOT NULL,
  `age_rating` VARCHAR(8) NOT NULL,
  `item_count` INT UNSIGNED NOT NULL,
  `description` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`avID`),
  UNIQUE INDEX `avID_UNIQUE` (`avID` ASC) VISIBLE,
  CONSTRAINT `avBarcodeNumber`
    FOREIGN KEY (`avID`)
    REFERENCES `Items` (`item_barcode_number`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Fiction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Fiction` ;

CREATE TABLE IF NOT EXISTS `Fiction` (
  `fictionID` INT UNSIGNED NOT NULL,
  `genre` VARCHAR(16) NOT NULL,
  `author_first_name` VARCHAR(32) NOT NULL,
  `author_last_name` VARCHAR(32) NOT NULL,
  `age_rating` VARCHAR(8) NOT NULL,
  `description` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`fictionID`),
  UNIQUE INDEX `fictionID_UNIQUE` (`fictionID` ASC) VISIBLE,
  CONSTRAINT `fictionBarcodeNumber`
    FOREIGN KEY (`fictionID`)
    REFERENCES `Items` (`item_barcode_number`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NonFiction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `NonFiction` ;

CREATE TABLE IF NOT EXISTS `NonFiction` (
  `nonFictionID` INT UNSIGNED NOT NULL,
  `deweydecimal` DECIMAL(32) UNSIGNED NOT NULL,
  `library_of_congress_classification` VARCHAR(32) NOT NULL,
  `topic` VARCHAR(16) NOT NULL,
  `author_first_name` VARCHAR(32) NOT NULL,
  `author_last_name` VARCHAR(32) NOT NULL,
  `age_rating` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`nonFictionID`),
  UNIQUE INDEX `nonFictionID_UNIQUE` (`nonFictionID` ASC) VISIBLE,
  CONSTRAINT `nonFictionBarcodeNumber`
    FOREIGN KEY (`nonFictionID`)
    REFERENCES `Items` (`item_barcode_number`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Archival`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Archival` ;

CREATE TABLE IF NOT EXISTS `Archival` (
  `archivalID` INT UNSIGNED NOT NULL,
  `deweyDecimal` DECIMAL(32) UNSIGNED NOT NULL,
  `library_of_congress_classification` VARCHAR(32) NOT NULL,
  `item_count` INT UNSIGNED NOT NULL,
  `description` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`archivalID`),
  UNIQUE INDEX `archivalID_UNIQUE` (`archivalID` ASC) VISIBLE,
  CONSTRAINT `archivalBarcodeNumber`
    FOREIGN KEY (`archivalID`)
    REFERENCES `Items` (`item_barcode_number`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Kit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Kit` ;

CREATE TABLE IF NOT EXISTS `Kit` (
  `kitId` INT UNSIGNED NOT NULL,
  `age_rating` VARCHAR(8) NOT NULL,
  `item_count` INT UNSIGNED NOT NULL,
  `description` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`kitId`),
  UNIQUE INDEX `kitId_UNIQUE` (`kitId` ASC) VISIBLE,
  CONSTRAINT `kitBarcodeNumber`
    FOREIGN KEY (`kitId`)
    REFERENCES `Items` (`item_barcode_number`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Periodical`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Periodical` ;

CREATE TABLE IF NOT EXISTS `Periodical` (
  `periodicalID` INT UNSIGNED NOT NULL,
  `publisher` VARCHAR(32) NOT NULL,
  `age_rating` VARCHAR(8) NOT NULL,
  `issue_date` DATE NOT NULL,
  `volume` INT UNSIGNED NULL,
  `issue` INT UNSIGNED NULL,
  PRIMARY KEY (`periodicalID`),
  UNIQUE INDEX `periodicalID_UNIQUE` (`periodicalID` ASC) VISIBLE,
  CONSTRAINT `periodicalBarcodeNumber`
    FOREIGN KEY (`periodicalID`)
    REFERENCES `Items` (`item_barcode_number`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pass`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pass` ;

CREATE TABLE IF NOT EXISTS `Pass` (
  `passID` INT UNSIGNED NOT NULL,
  `item_count` INT UNSIGNED NOT NULL,
  `description` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`passID`),
  UNIQUE INDEX `passID_UNIQUE` (`passID` ASC) VISIBLE,
  CONSTRAINT `passBarcodeNumber`
    FOREIGN KEY (`passID`)
    REFERENCES `Items` (`item_barcode_number`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Digital`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Digital` ;

CREATE TABLE IF NOT EXISTS `Digital` (
  `digitalID` INT UNSIGNED NOT NULL,
  `content_length` VARCHAR(32) NOT NULL,
  `description` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`digitalID`),
  UNIQUE INDEX `digitalID_UNIQUE` (`digitalID` ASC) VISIBLE,
  CONSTRAINT `digitalBarcodeNumber`
    FOREIGN KEY (`digitalID`)
    REFERENCES `Items` (`item_barcode_number`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Transactions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Transactions` ;

CREATE TABLE IF NOT EXISTS `Transactions` (
  `transactionID` INT UNSIGNED NOT NULL,
  `patronCardNumber` INT UNSIGNED NOT NULL,
  `transactionBranch` INT UNSIGNED NULL,
  `transactionItem` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`transactionID`),
  UNIQUE INDEX `transactionID_UNIQUE` (`transactionID` ASC) VISIBLE,
  INDEX `patronCardNumber_idx` (`patronCardNumber` ASC) VISIBLE,
  INDEX `transactionBranchID_idx` (`transactionBranch` ASC) VISIBLE,
  INDEX `transactionItemBarcodeNumber_idx` (`transactionItem` ASC) VISIBLE,
  CONSTRAINT `patronCardNumber`
    FOREIGN KEY (`patronCardNumber`)
    REFERENCES `Patrons` (`libraryCardNumber`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `transactionBranchID`
    FOREIGN KEY (`transactionBranch`)
    REFERENCES `Library Branches` (`branchID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `transactionItemBarcodeNumber`
    FOREIGN KEY (`transactionItem`)
    REFERENCES `Items` (`item_barcode_number`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Payments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Payments` ;

CREATE TABLE IF NOT EXISTS `Payments` (
  `paymentID` INT UNSIGNED NOT NULL,
  `total_paid` DECIMAL(4) UNSIGNED NOT NULL,
  `date_of_payment` DATE NOT NULL,
  PRIMARY KEY (`paymentID`),
  UNIQUE INDEX `paymentID_UNIQUE` (`paymentID` ASC) VISIBLE,
  CONSTRAINT `paymentTransactionID`
    FOREIGN KEY (`paymentID`)
    REFERENCES `Transactions` (`transactionID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Holds`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Holds` ;

CREATE TABLE IF NOT EXISTS `Holds` (
  `holdID` INT UNSIGNED NOT NULL,
  `owningBranch` INT UNSIGNED NOT NULL,
  `holdingBranch` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`holdID`),
  UNIQUE INDEX `holdID_UNIQUE` (`holdID` ASC) VISIBLE,
  INDEX `owningBranchID_idx` (`owningBranch` ASC) VISIBLE,
  INDEX `holdingBranchID_idx` (`holdingBranch` ASC) VISIBLE,
  CONSTRAINT `holdTransactionID`
    FOREIGN KEY (`holdID`)
    REFERENCES `Transactions` (`transactionID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Checkouts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Checkouts` ;

CREATE TABLE IF NOT EXISTS `Checkouts` (
  `checkoutID` INT UNSIGNED NOT NULL,
  `checkoutBranch` INT UNSIGNED NOT NULL,
  `checkout_date` DATE NOT NULL,
  PRIMARY KEY (`checkoutID`),
  UNIQUE INDEX `checkoutID_UNIQUE` (`checkoutID` ASC) VISIBLE,
  INDEX `checkoutBranchID_idx` (`checkoutBranch` ASC) VISIBLE,
  CONSTRAINT `checkoutTransactionID`
    FOREIGN KEY (`checkoutID`)
    REFERENCES `Transactions` (`transactionID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Returns`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Returns` ;

CREATE TABLE IF NOT EXISTS `Returns` (
  `returnID` INT UNSIGNED NOT NULL,
  `returnBranch` INT UNSIGNED NOT NULL,
  `return_date` DATE NOT NULL,
  PRIMARY KEY (`returnID`),
  UNIQUE INDEX `returnID_UNIQUE` (`returnID` ASC) VISIBLE,
  INDEX `returnBranchID_idx` (`returnBranch` ASC) VISIBLE,
  CONSTRAINT `returnTransactionID`
    FOREIGN KEY (`returnID`)
    REFERENCES `Transactions` (`transactionID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
